config/routes.rb
Rails.application.routes.draw do

  get "organizations/landing/:id", to: "organizations#landingpage", as: "org_landing"
  get "organizations/profile/:id", to: "organizations#profilepage", as: "org_profile"
  resources :organizations do
    resources :newsposts
    resources :banks
  end

  get 'home/index'
  get 'search/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'donors/new', to: 'donors#new', as: 'new_donor'
  post 'donors', to: 'donors#create'
  get 'donors/:id', to: 'donors#donor_home', as: 'donor'
  get 'donors/:id/profile', to: 'donors#profile', as: 'profile_donor'
  get 'donors/:id/edit', to: 'donors#edit', as: 'edit_donor'
  get 'donors/:id/edit_donation', to: 'donors#edit_donation', as: 'edit_donation'
  put 'donors/:id', to: 'donors#update'
  patch 'donors/:id', to: 'donors#update'
  
  resources :donors do
    resources :notifications
    resources :cards
  end
  

  get 'payments/:id/edit', to: 'payments#edit', as: 'edit_payment'
  get 'payments/:id/donor/:donorid/new', to: 'payments#new', as: 'new_payment'
  post 'payments', to: 'payments#create'
  get 'payments/:id', to: 'payments#show', as: 'payment'
  put 'payments/:id', to: 'payments#update'
  patch 'payments/:id', to: 'payments#update'
  delete 'payments/:id', to: 'payments#destroy'

  
  root to: "home#index"

end

app/models/donor.rb
# == Schema Information
#
# Table name: donors
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  dob        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_donors_on_user_id  (user_id)
#

class Donor < ApplicationRecord

    
    
	belongs_to :user, optional:true
    has_many :payments
    has_many :cards
    has_many :notifications
    has_many :donor_tags
    has_many :organizations, through: :payments
    has_many :tags, through: :donor_tags

    validates :name, length: { maximum: 30 }, presence: true
    validates_format_of :dob, :with => /\d{2}\/\d{2}\/\d{4}/, :message => "Date must be in the following format: mm/dd/yyyy", presence: true
    validate :address_verification


    def address_verification
  
        if ( (address != nil) && (StreetAddress::US.parse_address(address) == nil))
          errors.add(:address, "Invalid Format, Use specified")
        end

    end    
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
    before_action :set_donor, only: [:edit, :update]

    def donor_home
      @donor = Donor.find(params[:id])
      @tag = DonorTag.find_by_donor_id(@donor.id)
      #render donors/donor_home.html.erb
    end
    
    def new
      @donor = Donor.new
      @all_tags = Tag.all
      @donor_tag = @donor.donor_tags.build
      #render donors/new.html.erb
    end    

    def edit
      @donor = Donor.find(params[:id])
      @all_tags = Tag.all
      @donor_tag = @donor.donor_tags.build
      @selected_tags = @donor.donor_tags  
      #render donors/edit.html.erb
    end

    def profile
      @donor = Donor.find(params[:id])
      #render donors/profile.html.erb
    end


    def edit_donation
      @donor = Donor.find(params[:id])
      #render donors/edit_donation.html.erb
    end
  
     # POST /donors
    def create
      @donor = Donor.new(user: current_user, name: params[:donor][:name],
                       address: params[:donor][:address],
                       dob: params[:donor][:dob])
      
      params[:tags][:id].each do |tag|
            if !tag.empty?
              @donor.donor_tags.build(:tag_id => tag)
            end
        end

        if @donor.save
            flash[:notice] = "Donor profile saved successfully!"
            redirect_to :action => "donor_home", :id => @donor
        else
            @all_tags = Tag.all
            @donor_tag = @donor.donor_tags.build
            flash.now[:alert] = "Donor profile save failed!"
            render :new
        end                              
    end

    #PATCH/PUT /donors/1
    def update
      @donor = Donor.find(params[:id])
      
      @donor.donor_tags.each do |t|
        t.destroy
      end

      params[:tags][:id].each do |tag|
        if !tag.empty?
          @donor.donor_tags.build(:tag_id => tag)
        end
      end                                   
  
        if @donor.update(user: current_user, name: params[:donor][:name],
                         address: params[:donor][:address],
                         dob: params[:donor][:dob])
          
            flash[:notice] = "Donor profile updated successfully!"
            redirect_to :action => "donor_home", :id => @donor
        else
            @all_tags = Tag.all
            @donor_tag = @donor.donor_tags.build
            @selected_tags = @donor.donor_tags
            flash.now[:alert] = "Donor profile update failed!"
            render :edit
        end                          
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      @donor = Donor.find(params[:id])
    end
    
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/donor_home.html.erb
<% if user_signed_in?  && @donor.user_id == current_user.id %>
<div class="container">
  <div class="row">
  <h1> Donor homepage</h1>

  <div class="col-md-12">
  	 <!-- Sidebar Widgets Column -->
      <div class="card my-4">
        <h5 class="card-header">Welcome, <%=@donor.name%></h5>
        <div class="card-body">
          <div class="input-group">
			<table class="table">
    				<thead>
    				<tr>
    					<th scope="col">#</th>
    					<th scope="col">OrgName</th>
    					<th scope="col">Amount</th>
    					<th scope="col">Edit</th>
    					<th scope="col">Delete</th>
    				</tr>
    				</thead>

            <tbody>
                    <% i = 1%>
    				<% @donor.payments.each do |payment|%>
    				<tr>
    					 <th scope="row"><%= i %></th>
    					 <td><%= link_to payment.organization.name, org_profile_path(payment.organization, :donor => @donor) %></td>
    					 <td>$<%= payment.amount %></td>
    					 <td><%= link_to 'Edit', edit_payment_path(payment)%></td>
                         <td><%= link_to 'Delete', payment_path(payment), method: :delete%></td>
                         <%i = i + 1%>
    				</tr>
    				<% end %>
    				<tr>
    					 <th scope="row"></th>
    					 <td>Total Amount</td>
    					 <td>$<%= @donor.payments.sum(:amount)%></td>
    					 <td></td>
    					 <td></td>
    				</tr>
    				</tbody>
            </table>
         </div>
         </div>
         </div>
    </div>

    <!-- Suggested Organizations Entries Column -->
    <div class="col-md-12">

      <h2 class="my-4">Suggested organizations based on your tags</h2>

      <% if @tag != nil%>
        <% @donor.tags.each do |t|%>
          <% t.organizations.each do |o|%>
            <div class="card mb-4">
              <div class="card-body">
                <h2 class="card-title"><%= o.name %></h2>
                <p class="card-text"><%= o.about %></p>
                <%= link_to 'Organization Profile', org_profile_path(o, :donor => @donor), {:class => "btn btn-primary"}%> &rarr;
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

    </div>
    
   
  </div> <!-- /.row -->
</div> <!-- /.container -->
<% end %>

app/views/donors/edit.html.erb

<script type="text/javascript">
      $(document).ready(function(){
        var startYear = new Date();
        startYear.setFullYear(startYear.getFullYear() - 100);
        var endYear = new Date();
        endYear.setFullYear(endYear.getFullYear() - 18);
        $('.datepicker').datepicker({
           autoclose:true,
           startDate: startYear,
           endDate: endYear
        });
      });
      </script>

<% if user_signed_in? %>
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Edit Profile</h5>
        <div class="card-body">
          <div class="input-group">
            <% if @donor.errors.any?%>
                <div style="background-color: #FF0000">
                <p>
                Please fix the following errors:
                </p>
                <ul>
                <% @donor.errors.full_messages.each do |message|%>
                  <li><%= message%></li>
                  <% end %>
                </ul>
                </div>
                  
            <% end%>
          
            <%= form_for @donor do |d|%>
              <p>
              <strong>Name:</strong><br>
              <%= d.text_field :name, placeholder: 'Enter Name'%>
              </p>

              <p>
              <strong>Address:</strong><br>
              <%= d.text_field :address, placeholder: 'Enter Address'%>
              </p>

              <p>
              <strong>DOB:</strong><br>
              <%= d.text_field :dob, class:"datepicker", placeholder: 'MM/dd/YYYY'%>
              </p>

              <p>
              <%= fields_for (@donor_tag) do |dt|%>
                <strong><%= dt.label "Tags:" %></strong><br>
              <%= collection_select(:tags, :id, @all_tags, :id, :name, {:selected => @selected_tags.collect {|tag| tag.tag_id}}, {:multiple => true, :id => "tags"}) %>
              
               <% end %>                          
              </p>

              <p>
              <%= d.submit "Update Donor"%>
              </p>
              <% end %> <!--End of form-->
          
        </div>
        </div>
        </div>
        </div>
        </div> <!-- /.row -->
  </div> <!-- /.container -->
<% end %> <!--End of user signed in-->
   


app/views/donors/edit_donation.html.erb
<h1> Edit Donation </h1>

<table>
<tr>
<th>OrgName</th>
<th> </th>
<th>Amount</th>
<th>RecurringType</th>
<th></th>
</tr>

<% @donor.payments.each do |payment|%>
<tr>
    <td><%= payment.organization.name %><td>
    <td><%= payment.amount %></td>
    <td><%= payment.paymentType %></td>
    <td>
    <%= link_to 'Edit', edit_payment_path(payment)%>
    <%= link_to 'Delete', payment_path(payment), method: :delete%>

   </td>
    </tr>
    <% end %>

</table>

app/views/donors/new.html.erb

<script type="text/javascript" data-turbolinks-eval=false>
      $(document).ready(function(){
        var startYear = new Date();
        startYear.setFullYear(startYear.getFullYear() - 100);
        var endYear = new Date();
        endYear.setFullYear(endYear.getFullYear() - 18);
        $('.datepicker').datepicker({
           autoclose:true,
           startDate: startYear,
           endDate: endYear
        });
      });
      </script>

<% if user_signed_in? %>
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Create Profile</h5>
        <div class="card-body">
          <div class="input-group">
            <% if @donor.errors.any?%>
                <div style="background-color: #FF0000">
                <p>
                Please fix the following errors:
                </p>
                <ul>
                <% @donor.errors.full_messages.each do |message|%>
                  <li><%= message%></li>
                  <% end %>
                </ul>
                </div>
                  
            <% end%>
          
            <%= form_for @donor do |d|%>
              <p>
              <strong>Name:</strong><br>
              <%= d.text_field :name, placeholder: 'Enter Name'%>
              </p>

              <p>
              <strong>Address:</strong><br>
              <%= d.text_field :address, placeholder: 'Enter Address'%>
              </p>

              <p>
              <strong>DOB:</strong><br>
              <%= d.text_field :dob, class:"datepicker", placeholder: 'MM/dd/YYYY'%>
              </p>

              <p>
              <%= fields_for (@donor_tag) do |dt|%>
                <strong><%= dt.label "Tags:" %></strong>&nbsp <span>(multiple select using Ctrl+click) </span><br>
              <%= collection_select(:tags, :id, @all_tags, :id, :name, {}, {:multiple => true, :id => "tags"}) %>
              
               <% end %>                          
              </p>

              <p>
              <%= d.submit "Create Donor"%>
              </p>
              <% end %> <!--End of form-->
          
        </div>
        </div>
        </div>
        </div>
        </div> <!-- /.row -->
  </div> <!-- /.container -->
<% end %> <!--End of user signed in-->
   



   

app/views/donors/profile.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-8">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Profile</h5>
        <div class="card-body">
          <% if user_signed_in? && current_user.donor %>
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Name:</strong>
              <%= @donor.name %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @donor.address %>
            </p>

            <p>
              <strong>DOB:</strong>
              <%= @donor.dob %>
            </p>

            <% if @donor.tags.any? %>
            <p>
              <strong>Tags:</strong>
              <% @donor.tags.each do |t|%>
                <span class="badge badge-secondary"><%=t.name%></span>
              <% end%>
            </p>
            <% end%>                          
  

          <p>
            <%= link_to 'Edit', edit_donor_path(@donor) %> |
            <%= link_to 'Back', donor_path(@donor) %>
          </p>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>