config/routes.rb
Rails.application.routes.draw do

  get "organizations/landing/:id", to: "organizations#landingpage", as: "org_landing"
  get "organizations/profile/:id", to: "organizations#profilepage", as: "org_profile"
  resources :organizations do
    resources :newsposts
    resources :banks
  end

  get 'home/index'
  get 'search/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'donors/new', to: 'donors#new', as: 'new_donor'
  post 'donors', to: 'donors#create'
  get 'donors/:id', to: 'donors#donor_home', as: 'donor'
  get 'donors/:id/profile', to: 'donors#profile', as: 'profile_donor'
  get 'donors/:id/edit', to: 'donors#edit', as: 'edit_donor'
  get 'donors/:id/edit_donation', to: 'donors#edit_donation', as: 'edit_donation'
  put 'donors/:id', to: 'donors#update'
  patch 'donors/:id', to: 'donors#update'
  
  resources :donors do
    resources :notifications
    resources :cards
  end
  

  get 'payments/:id/edit', to: 'payments#edit', as: 'edit_payment'
  get 'payments/:id/donor/:donorid/new', to: 'payments#new', as: 'new_payment'
  post 'payments', to: 'payments#create'
  get 'payments/:id', to: 'payments#show', as: 'payment'
  put 'payments/:id', to: 'payments#update'
  patch 'payments/:id', to: 'payments#update'
  delete 'payments/:id', to: 'payments#destroy'

  
  root to: "home#index"

end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  donor_id   :integer
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_notifications_on_donor_id  (donor_id)
#

class Notification < ApplicationRecord
  belongs_to :donor

  validates :title, length: { maximum: 30 }, presence: true
  validates :content, length: { maximum: 120 }, presence: true


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notifications
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET donors/1/notifications
  def index
    @notifications = @donor.notifications
  end

  # GET donors/1/notifications/1
  def show
  end

  # GET donors/1/notifications/new
  def new
    @notification = @donor.notifications.build
  end

  # GET donors/1/notifications/1/edit
  def edit
  end

  # POST donors/1/notifications
  def create
    #@notification = @donor.notifications.build(notification_params)

    Donor.all.each do |d|
      @x= d.notifications.build(notification_params)
      @x.save
    end

    #if @notification.save
      redirect_to(root_path, notice: 'Notification was successfully created.')
    #else
    #  render action: 'new'
    #end
  end

  # PUT donors/1/notifications/1
  def update
    if @notification.update_attributes(notification_params)
      redirect_to([@notification.donor, @notification], notice: 'Notification was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE donors/1/notifications/1
  def destroy
    @notification.destroy

    redirect_to donor_notifications_url(@donor)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notifications
      @donor = Donor.find(params[:donor_id])
      if current_user.organization?
        @organization = Organization.where("user_id = #{current_user.id}").take!
      end
    end

    def set_notification
      @notification = @donor.notifications.find(params[:id])

    end

    # Only allow a trusted parameter "white list" through.
    def notification_params
      params.require(:notification).permit(:title, :content)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for([@notification.donor, @notification]) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', [@notification.donor, @notification] %> |
<%= link_to 'Back', donor_notifications_path(@notification.donor) %>

app/views/notifications/index.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-8">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Listing notifications</h5>
        <div class="card-body">
          <div class="input-group">

          <table class="table">
            <tr>
              <th>Title</th>
              <th>Content</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>

          <% @notifications.each do |notification| %>
            <tr>
              <td><%= notification.title %></td>
              <td><%= notification.content %></td>
              <td><%= link_to 'Delete', [notification.donor, notification], :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
          <% end %>
          </table>

          <br />

          <% if current_user and current_user.organization %>
          <%= link_to 'New Notification', new_donor_notification_path(params[:donor_id]) %>
          <%end%>

      </div>
      </div>
   </div>
  </div>
  </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/notifications/new.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">News Notification</h5>
        <div class="card-body">
          <% if user_signed_in?  && @organization.user_id == current_user.id %>
          <div class="input-group">
			<%= render 'form' %>
		  </div>
		  <%= link_to 'Back', donor_notifications_path(@notification.donor) %>
		  <%end%>
	    </div>
	 </div>
	</div>
  </div> <!-- /.row -->
</div> <!-- /.container -->

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @notification.title %>
</p>

<p>
  <b>Content:</b>
  <%= @notification.content %>
</p>


<%= link_to 'Edit', edit_donor_notification_path(@notification.donor, @notification) %> |
<%= link_to 'Back', donor_notifications_path(@notification.donor) %>