config/routes.rb
Rails.application.routes.draw do

  get "organizations/landing/:id", to: "organizations#landingpage", as: "org_landing"
  get "organizations/profile/:id", to: "organizations#profilepage", as: "org_profile"
  resources :organizations do
    resources :newsposts
    resources :banks
  end

  get 'home/index'
  get 'search/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'donors/new', to: 'donors#new', as: 'new_donor'
  post 'donors', to: 'donors#create'
  get 'donors/:id', to: 'donors#donor_home', as: 'donor'
  get 'donors/:id/profile', to: 'donors#profile', as: 'profile_donor'
  get 'donors/:id/edit', to: 'donors#edit', as: 'edit_donor'
  get 'donors/:id/edit_donation', to: 'donors#edit_donation', as: 'edit_donation'
  put 'donors/:id', to: 'donors#update'
  patch 'donors/:id', to: 'donors#update'
  
  resources :donors do
    resources :notifications
    resources :cards
  end
  

  get 'payments/:id/edit', to: 'payments#edit', as: 'edit_payment'
  get 'payments/:id/donor/:donorid/new', to: 'payments#new', as: 'new_payment'
  post 'payments', to: 'payments#create'
  get 'payments/:id', to: 'payments#show', as: 'payment'
  put 'payments/:id', to: 'payments#update'
  patch 'payments/:id', to: 'payments#update'
  delete 'payments/:id', to: 'payments#destroy'

  
  root to: "home#index"

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string
#  owner      :string
#  website    :string
#  address    :string
#  year       :integer
#  about      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_organizations_on_user_id  (user_id)
#


class Organization < ApplicationRecord
  has_many :banks
  belongs_to :user , optional:true
  has_many :newsposts
  has_many :payments
  has_many :organization_tags
  has_many :bank_accounts
  has_many :donors, through: :payments
  has_many :tags, through: :organization_tags



  validates :name, length: { maximum: 40 }, presence: true
  validates :owner, length: { maximum: 30 }, presence: true
  validates :website, format: { with: /https?:\/\/[\S]+/  }, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1700, less_than_or_equal_to: 2018, allow_nil: true }, allow_nil: true, allow_blank: true
  validate :address_verification

  private
 
  def address_verification
  
    if ( (address != nil) && (StreetAddress::US.parse_address(address) == nil))
      errors.add(:address, "Invalid Format, Use specified")
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def landingpage
    @organization = Organization.find(params[:id])
    @newsposts = @organization.newsposts
  end

  def profilepage
    if params.has_key?(:donor)
      @donor = Donor.find(params[:donor]) # to display the nav menu correctly to logged in donor
    end
    @organization = Organization.find(params[:id])
    @newsposts = @organization.newsposts
      
    
  end

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @all_tags = Tag.all
    @organization_tag = @organization.organization_tags.build
    @selected_tags = @organization.organization_tags  
    
  end

  # GET /organizations/1/edit
  def edit
    end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    
    params[:tags][:id].each do |tag|
      if !tag.empty?
        @organization.organization_tags.build(:tag_id => tag)
      end
  end

    respond_to do |format|
      if @organization.save
        id= @organization.id
        format.html { redirect_to org_landing_path(id), notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        @all_tags = Tag.all
        @organization_tag = @organization.organization_tags.build
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      @organization.organization_tags.each do |t|
        t.destroy
      end

      params[:tags][:id].each do |tag|
        if !tag.empty?
          @organization.organization_tags.build(:tag_id => tag)
        end
      end
      
        if @organization.update(organization_params)
          id= @organization.id
          format.html { redirect_to org_landing_path(id), notice: 'Organization was successfully updated.' }
          format.json { render :show, status: :ok, location: @organization }
        else
          params[:tags][:id].each do |tag|
            if !tag.empty?
              @organization.organization_tags.build(:tag_id => tag)
            end
          end
          @all_tags = Tag.all
          @organization_tag = @organization.organization_tags.build
          @selected_tags = @organization.organization_tags
          format.html { render :edit }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
      @all_tags = Tag.all
      @organization_tag = @organization.organization_tags.build
      @selected_tags = @organization.organization_tags  
   
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      # Pass in the logged in user
      defaults = { user: current_user }
      params.require(:organization).permit(:user, :name, :owner,
                                           :website, :address,
                                           :year, :about, :id,).reverse_merge(defaults)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if user_signed_in? %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organization_name, :class => "form-control"%>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner, id: :organization_owner, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :organization_website, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :organization_address, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :organization_year, :class => "form-control", :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about, id: :organization_about, :class => "form-control" %>
  </div>

  <p>
  <% if @selected_tags != nil %>
  
  <%= fields_for (@organization_tag) do |ot|%>
    <div class="field">
    <%= ot.label "Tags:" %><br>
  <%= collection_select(:tags, :id, @all_tags, :id, :name, {:selected => @selected_tags.collect {|tag| tag.tag_id}}, {:multiple => true, :id => "tags"}) %>
  </div>
  <% end %>
  
  <% else%>
  <%= fields_for (@organization_tag) do |ot|%>
    <div class="field">
    <%= ot.label "Tags:" %>&nbsp <span>(multiple select using Ctrl+click) </span><br>
  <%= collection_select(:tags, :id, @all_tags, :id, :name, {}, {:multiple => true, :id => "tags"}) %>
  </div>
  
  <% end %> 
 
  <% end %><!--End Of organization_tags-->    
  </p>        

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %> <!--End of user signed in-->
<% end %> <!--End of form-->

app/views/organizations/edit.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Edit Profile</h5>
        <div class="card-body">
          <% if user_signed_in? && @organization.user_id == current_user.id %>
            <div class="input-group">
              <p id="notice"><%= notice %></p>
			  <%= render 'form', organization: @organization %>
		    </div>
		    <%= link_to 'Show', @organization %> |
			<%= link_to 'Back', org_landing_path(@organization) %>
		  <%end%>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Website</th>
      <th>Address</th>
      <th>Year</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.owner %></td>
        <td><%= organization.website %></td>
        <td><%= organization.address %></td>
        <td><%= organization.year %></td>
        <td><%= organization.about %></td>
        <td><%= link_to 'Show', organization %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/landingpage.html.erb
<% if user_signed_in?  && @organization.user_id == current_user.id %>
<div class="container">
  <div class="row">
  	<div class="col-md-12">
  	 <!-- Sidebar Widgets Column -->
      <div class="card my-4">
        <h5 class="card-header">Welcome, <%= @organization.name %></h5>
        <div class="card-body">
          <div class="input-group">
			<table class="table">

			<h2>Recent NewsPosts</h2>

			<table class="table">
				<thead>
					<tr>
					<th scope="col">#</th>
					<th scope="col">NewsPost</th>
					<th scope="col">Edit</th>
					<th scope="col">Delete</th>
					</tr>
				</thead>

				<tbody>
                <% i = 1%>
                	<tr>
					<% @organization.newsposts.each do |newspost| %>
					<th scope="row"><%= i %></th>
					<% var = newspost.title %>
					<td><%= link_to var, [@organization, newspost] %></td>
					<td><%= link_to 'Edit', edit_organization_newspost_path(@organization, newspost) %></td>
					<td><%= link_to 'Destroy', [@organization, newspost], :confirm => 'Are you sure?', :method => :delete %> </td>
					</tr>
				<% end %>
				</tbody>
			</table>

			<h2>Current Donations</h2>

			<table class="table">
				<thead>
					<tr>
					<th scope="col">#</th>
					<th scope="col">Donor</th>
					<th scope="col">Amount</th>
					</tr>
				</thead>

				<tbody>
	                <% i = 1%>
					<% @organization.payments.each do |payment|%>
					<tr>
					 <th scope="row"><%= i %></th>
					 <td><%= payment.donor.name %></td>
					 <td> <%= payment.amount %> $ </td>
					</tr>
					<%i = i+1%>
					<% end %>
					<tr>
						<td></td>
						<td>Total Amount</td>
						<td>$ <%= @organization.payments.sum(:amount) %></td>
					</tr>
				</tbody>
			</table>
		  </div>
	    </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/organizations/new.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Create profile</h5>
        <div class="card-body">
          <div class="input-group">
			<%= render 'form', organization: @organization %>
		  </div>
	    </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/profilepage.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
     <!-- Sidebar Widgets Column -->
      <div class="card my-8">
        <%if current_user != nil and current_user.organization?%>
        <h5 class="card-header">Welcome, <%= @organization.name %></h5>
        <%end%>
        <div class="card-body">
          <h1>
            Organization Name: <%= @organization.name %>
            <% if (user_signed_in? && current_user.donor?) %>
            <!--Not sure if this should be accessible to non-signed in user so that we redirect him to first sign in?-->
            <%= link_to 'Donate Now', new_payment_path(@organization,current_user.donor), :class => "btn btn-primary" %>
            <% end %>
          </h1>

          <p>
            <strong>Owner:</strong>
            <%= @organization.owner %>
          </p>

          <p>
            <strong>Website:</strong>
            <%= @organization.website %>
          </p>

          <p>
            <strong>Address:</strong>
            <%= @organization.address %>
          </p>

          <p>
            <strong>Year:</strong>
            <%= @organization.year %>
          </p>

          <p>
            <strong>About:</strong>
            <%= @organization.about %>
          </p>

          <p>
          <strong>Tags:</strong>
          <% @organization.tags.each do |t|%>
            <span class="badge badge-secondary"><%=t.name%></span>
          <% end%>
         </p>                          


          <h2>Recent News Posts</h2>
          
          <table class="table">
            <thead>
              <tr>
              <th scope="col">#</th>
              <th scope="col">News Post</th>
              </tr>
            </thead>
            <tbody>
              <% i = 1%>
              <% @organization.newsposts.each do |newspost| %>
              <tr>
                <td><%= i%></td>
                <% var = newspost.title %> 
                <td><%= link_to var, [@organization, newspost] %></td>
              </tr>
              <%i = i+1%>
              <% end %>
            </tbody>

          </table>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Sidebar Widgets Column -->
    <div class="col-md-8">

      <!-- Login Widget -->
      <div class="card my-4">
        <h5 class="card-header">Profile</h5>
        <div class="card-body">
          <% if user_signed_in? && @organization.user_id == current_user.id %>
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Name:</strong>
              <%= @organization.name %>
            </p>

            <p>
              <strong>Owner Name:</strong>
              <%= @organization.owner %>
            </p>

            <p>
              <strong>Website:</strong>
              <%= @organization.website %>
            </p>

            <p>
              <strong>Address:</strong>
              <%= @organization.address %>
            </p>

            <p>
              <strong>Year:</strong>
              <%= @organization.year %>
            </p>

            <p>
              <strong>About:</strong>
              <%= @organization.about %>
            </p>
            <% if @organization.tags != nil%>
            <p>
              <strong>Tags:</strong>
              <% @organization.tags.each do |t|%>
                <span class="badge badge-secondary"><%=t.name%></span>
              <% end%>
            </p>
            <% end%>                          
  

          <p>
            <%= link_to 'Edit', edit_organization_path(@organization) %> |
            <%= link_to 'Back', org_landing_path(@organization) %>
          </p>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>