config/routes.rb
Rails.application.routes.draw do

  get "organizations/landing/:id", to: "organizations#landingpage", as: "org_landing"
  get "organizations/profile/:id", to: "organizations#profilepage", as: "org_profile"
  resources :organizations do
    resources :newsposts
    resources :banks
  end

  get 'home/index'
  get 'search/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'donors/new', to: 'donors#new', as: 'new_donor'
  post 'donors', to: 'donors#create'
  get 'donors/:id', to: 'donors#donor_home', as: 'donor'
  get 'donors/:id/profile', to: 'donors#profile', as: 'profile_donor'
  get 'donors/:id/edit', to: 'donors#edit', as: 'edit_donor'
  get 'donors/:id/edit_donation', to: 'donors#edit_donation', as: 'edit_donation'
  put 'donors/:id', to: 'donors#update'
  patch 'donors/:id', to: 'donors#update'
  
  resources :donors do
    resources :notifications
    resources :cards
  end
  

  get 'payments/:id/edit', to: 'payments#edit', as: 'edit_payment'
  get 'payments/:id/donor/:donorid/new', to: 'payments#new', as: 'new_payment'
  post 'payments', to: 'payments#create'
  get 'payments/:id', to: 'payments#show', as: 'payment'
  put 'payments/:id', to: 'payments#update'
  patch 'payments/:id', to: 'payments#update'
  delete 'payments/:id', to: 'payments#destroy'

  
  root to: "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>SupportR</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style type="text/css">
      body {
        padding-top: 54px;
      }

      @media (min-width: 992px) {
      body {
          padding-top: 56px;
        }
      }
    </style>

  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <div class="col-sm-offset-4">
            <%= form_tag(search_index_path, :method => "get") do %>
              <div class="input-group">
                <%= text_field_tag :search, params[:search], placeholder: "Search Organizations", class: 'form-control' %>
                <span class="input-group-btn">
                <%= submit_tag 'Go!', name: nil, :class => "btn btn-secondary" %>
                </span>
              </div>
            <% end %>
          </div>
          <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
              <%= link_to 'Home', home_index_path, {:class => "nav-link"}%>
              <span class="sr-only">(current)</span>
            </li>
            <% if user_signed_in? %>
              <% if current_user.role == "donor" and @donor != nil and @donor.id != nil %>
                <li class="nav-item">
                  <%= link_to 'Profile', profile_donor_path(@donor), :class => "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Payment methods', donor_cards_path(@donor), :class => "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Notifications', donor_notifications_path(@donor), :class => "nav-link"%>
                </li>
              <% elsif current_user.role == "organization" and @organization != nil and @organization.id != nil %>
                <li class="nav-item">
                  <%= link_to 'Profile', organization_path(@organization), :class => "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Create New Post', new_organization_newspost_path(@organization), :class => "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Bank Details', organization_banks_path(@organization), :class => "nav-link"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Send Notifications', new_donor_notification_path(1), :class => "nav-link"%>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "nav-link"%>
              </li>
            <%else%>
              <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, {:class => "nav-link"}%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

     <% if flash[:alert] %>
      <p style="background-color: #FF0000">
        <%= flash[:alert] %>
      </p>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <%end%>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <%end%>

    <%= yield %>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; SupportR 2018</p>
      </div>
      <!-- /.container -->
    </footer>

  </body>
</html>